import "./globals.css";
import Link from "next/link";
import ChatbotLauncher from "../components/ChatbotLauncher";
import Footer from "../components/Footer";
import NavToggle from "../components/NavToggle";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
      </head>
      <body className="antialiased">
        <header className="site-header">
          <nav className="primary-nav" role="navigation" aria-label="Main Navigation">
            <div className="nav-container">
              <div className="nav-logo">
                <Link href="/" aria-label="CFAFS Home">
                  <img src="/images/cfafs-logo.png" alt="CFAFS Logo" height="36" />
                </Link>
              </div>
              
              <NavToggle />
              
              <div id="primary-menu" className="nav-menu">
                <ul>
                  <li><Link href="/about">About</Link></li>
                  <li><Link href="/loans">Loans</Link></li>
                  <li><Link href="/membership">Membership</Link></li>
                  <li><Link href="/contact">Contact</Link></li>
                  <li><Link href="/board-members">Board Members</Link></li>
                  <li><Link href="/executive-leadership-team">Executive Leadership Team</Link></li>
                  <li><Link href="/account-login" className="login-btn">Account Login</Link></li>
                  <li><Link href="/careers">Careers</Link></li>
                  <li><Link href="/news">News</Link></li>
                </ul>
              </div>
            </div>
          </nav>
        </header>
        {children}
        <ChatbotLauncher />
        <Footer />
      </body>
    </html>
  );
}
