import "./globals.css";
import Link from "next/link";
import ChatbotLauncher from "../components/ChatbotLauncher";
import Footer from "../components/Footer";
import NavToggle from "../components/NavToggle";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
      </head>
      <body className="antialiased">
        <header className="site-header">
          <nav className="primary-nav" role="navigation" aria-label="Main Navigation">
            <div className="nav-container">
              <div className="nav-logo">
                <Link href="/" aria-label="CFAFS Home">
                  <img src="/images/cfafs-logo.png" alt="CFAFS Logo" height="36" />
                </Link>
              </div>
              <NavToggle />
              <div id="primary-menu" className="nav-menu">
                <ul style={{ justifyContent: 'flex-end', width: '100%' }}>
                  {/* About CFA Dropdown */}
                  <li className="dropdown">
                    <span tabIndex={0} className="dropdown-toggle">About CFA</span>
                    <ul className="dropdown-menu">
                      <li><Link href="/about#market-mission">Market & Mission</Link></li>
                      <li><Link href="/about#members">Members</Link></li>
                      <li><Link href="/about#soc-ii">SOC II & Certifications</Link></li>
                      <li><Link href="/board-members">Board of Directors</Link></li>
                      <li><Link href="/executive-leadership-team">CFA Executive Team</Link></li>
                    </ul>
                  </li>
                  {/* Products Dropdown */}
                  <li className="dropdown">
                    <span tabIndex={0} className="dropdown-toggle">Products</span>
                    <ul className="dropdown-menu">
                      <li><Link href="/loans#loan-products">Loan Products</Link></li>
                      <li><Link href="/loans#field-finance">Field Finance</Link></li>
                    </ul>
                  </li>
                  <li><Link href="/careers">Careers</Link></li>
                  <li><Link href="/about#developers">Partners</Link></li>
                  <li><Link href="/contact">Contact Us</Link></li>
                  <li><Link href="/news">Press</Link></li>
                  <li><Link href="/account-login" className="login-btn">Account Login</Link></li>
                </ul>
              </div>
            </div>
          </nav>
        </header>
        {children}
        <ChatbotLauncher />
        <Footer />
      </body>
    </html>
  );
}
